title: "吴宇辰的个人主页"
page-top-title: "吴宇辰"
top-section-bg-text: "计算机科学"
home-subtitle: "Yuchen Wu&ensp;|&ensp;吴宇辰"
nav-home: "首页"
nav-preprints: "在投论文"
nav-publications: "论文发表"
nav-projects: "项目"
nav-competitions: "竞赛经历"
nav-awards: "获奖荣誉"
preprints-subtitle: "<i class=\"bi bi-hourglass-split\"></i>&nbsp;在投论文"
publications-subtitle: "<i class=\"bi bi-file-text\"></i>&nbsp;论文发表"
projects-subtitle: "<i class=\"bi bi-code-slash\"></i>&nbsp;项目"
competitions-subtitle: "<i class=\"bi bi-trophy\"></i>&nbsp;竞赛经历"
awards-subtitle: "<i class=\"bi bi-award\"></i>&nbsp;获奖荣誉"
copyright-text: "Copyright &copy; 2024-2026 Yuchen Wu"
last-updated-label: "最后更新："
last-updated: "2026年4月21日"
